export const themes = {
  light: {
    primary: "bg-white",
    secondary: "bg-gray-50",
    text: "text-gray-900",
    textSecondary: "text-gray-600",
    textMuted: "text-gray-500",
    border: "border-gray-200",
    hover: "hover:bg-gray-50",
    accent: "text-blue-600",
    accentBg: "bg-blue-50",
    shadow: "shadow-sm",
    cardBg: "bg-white",
    sidebarBg: "bg-white",
    layoutBg: "bg-gray-50",
  },
  dark: {
    primary: "bg-gray-900",
    secondary: "bg-gray-800",
    text: "text-white",
    textSecondary: "text-gray-300",
    textMuted: "text-gray-400",
    border: "border-gray-700",
    hover: "hover:bg-gray-800",
    accent: "text-blue-400",
    accentBg: "bg-gray-800",
    shadow: "shadow-xl",
    cardBg: "bg-gray-900",
    sidebarBg: "bg-gray-900",
    layoutBg: "bg-gray-950",
  },
  colored: {
    primary: "bg-gradient-to-br from-purple-600 to-blue-600",
    secondary: "bg-gradient-to-r from-pink-500 to-orange-400",
    text: "text-white",
    textSecondary: "text-purple-100",
    textMuted: "text-purple-200",
    border: "border-purple-300",
    hover: "hover:bg-purple-700",
    accent: "text-yellow-300",
    accentBg: "bg-purple-700/50",
    shadow: "shadow-2xl shadow-purple-500/20",
    cardBg: "bg-white/10 backdrop-blur-lg",
    sidebarBg: "bg-white/5 backdrop-blur-lg",
    layoutBg: "bg-gradient-to-br from-purple-900 via-blue-900 to-indigo-900",
  },
};
